# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(null=True)),
                ('content', models.TextField()),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('open_to_public', models.BooleanField(default=False)),
                ('description', models.CharField(default='暂无简介', max_length=300)),
                ('read_num', models.IntegerField(default=0)),
                ('allow_comment', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('show', models.BooleanField(default=True)),
                ('grade', models.IntegerField(default=1)),
                ('show_in_header', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ColumnModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('grade', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.ColumnModel')),
            ],
            options={
                'db_table': 'columns',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='admin.ArticleModel')),
                ('reply_comments', models.ManyToManyField(related_name='_commentmodel_reply_comments_+', related_query_name='replied_comment', to='admin.CommentModel')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='DateArchiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Y', 'year'), ('M', 'm'), ('D', 'day')], default='Y', max_length=1)),
                ('date', models.CharField(max_length=2)),
                ('pre_grade', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_grades', related_query_name='next_grade', to='admin.DateArchiveModel')),
            ],
            options={
                'db_table': 'date_archive',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('show', models.BooleanField(default=True)),
                ('grade', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='VisitedRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.ArticleModel')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anony', max_length=50)),
                ('IP', models.GenericIPAddressField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('forbidden_visit', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(default='https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1667998903,1616440854&fm=27&gp=0.jpg')),
            ],
        ),
        migrations.AddField(
            model_name='visitedrecordmodel',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.VisitorModel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='admin.VisitorModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='categories',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='admin.CategoryModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='date_archives',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='admin.DateArchiveModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='admin.TagModel'),
        ),
    ]
