# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='open_to_public',
            field=models.BooleanField(default=False),
        ),
    ]
