# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_articlemodel_open_to_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='description',
            field=models.CharField(default='暂无简介', max_length=300),
        ),
    ]
