# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20170822_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tagmodel',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='categories',
            field=models.ManyToManyField(related_query_name='articles', to='admin.CategoryModel'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(related_query_name='articles', to='admin.TagModel'),
        ),
    ]
