# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0007_auto_20170822_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='readers_num',
            field=models.IntegerField(default=0),
        ),
    ]
