# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_articlemodel_readers_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='readers_num',
            new_name='read_num',
        ),
    ]
