# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0009_auto_20170823_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateArchiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Y', 'year'), ('M', 'm'), ('D', 'day')], default='Y', max_length=1)),
                ('date', models.IntegerField()),
                ('pre_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_grades', related_query_name='next_grade', to='admin.DateArchiveModel')),
            ],
            options={
                'db_table': 'date_archive',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='date_archive',
            field=models.ManyToManyField(related_name='articles', related_query_name='article', to='admin.DateArchiveModel'),
        ),
    ]
