# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0017_auto_20170824_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datearchivemodel',
            name='date',
            field=models.CharField(max_length=2),
        ),
    ]
