# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0018_auto_20170824_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
