# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0019_auto_20170824_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='grade',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
