# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0020_auto_20170824_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='meta',
            field=models.TextField(default=None, null=True),
        ),
    ]
