# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0024_auto_20170825_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedRecordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.ArticleModel')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anony', max_length=50)),
                ('IP', models.GenericIPAddressField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('visited_articles', models.ManyToManyField(related_name='visitors', related_query_name='visitor', through='admin.VisitedRecordModel', to='admin.ArticleModel')),
            ],
        ),
        migrations.AddField(
            model_name='visitedrecordmodel',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.VisitorModel'),
        ),
    ]
