# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0025_auto_20170829_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitormodel',
            name='visited_articles',
        ),
        migrations.AddField(
            model_name='visitormodel',
            name='forbidden_visit',
            field=models.BooleanField(default=True),
        ),
    ]
