# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0026_auto_20170829_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitormodel',
            name='forbidden_visit',
            field=models.BooleanField(default=False),
        ),
    ]
